import { AgentRegistry } from "../packages/agents/AgentRegistry";
import { createBoss } from "../packages/agents/Boss";
import { createManager } from "../packages/agents/Managers";
import { createWorker } from "../packages/agents/Workers";
import { OrganizationService } from "../packages/agents/Organization";
import { ConferenceRoomService } from "../packages/agents/ConferenceRoom";
import { AgentMessageService } from "../packages/messaging/AgentMessages";
import { ManagerAllocationService } from "../packages/orchestration/ManagerAllocation";
import { TaskDispatcher } from "../packages/orchestration/TaskDispatcher";
import { AgentRuntime } from "../packages/agents/Runtime";
import { DependencyManager } from "../packages/orchestration/Dependencies";
import { DelegationService } from "../packages/orchestration/Delegation";
import { Scheduler } from "../packages/orchestration/Scheduler";
import { ApprovalEngine } from "../packages/governance/ApprovalEngine";
import { DelegationFirewall } from "../packages/governance/DelegationFirewall";
import { PermissionEngine } from "../packages/governance/PermissionEngine";
import { PolicyEngine } from "../packages/governance/PolicyEngine";
import { IdentityService } from "../packages/security/Identity";
import { AccessControlService } from "../packages/security/AccessControl";
import { RiskEngine } from "../packages/security/RiskEngine";
import { AnomalyDetectionService } from "../packages/security/AnomalyDetection";
import { KillSwitchService } from "../packages/security/KillSwitch";
import { SecurityGateway } from "../packages/security/SecurityGateway";
import { WalletService } from "../packages/economy/Wallet";
import { AuditLedger } from "../packages/audit/AuditLedger";
import { AuditEventBridge } from "../packages/audit/EventBridge";
import { EventBus } from "../packages/messaging/EventBus";
import type { ExecutionEvents } from "../packages/agents/Execution";

const registry = new AgentRegistry();
const boss = createBoss("boss", "Boss");
const managerA = createManager("manager-a", "Manager A", boss.id);
const managerB = createManager("manager-b", "Manager B", boss.id);
const worker = createWorker("worker-a", "Worker A", managerA.id);
for (const agent of [boss, managerA, managerB, worker]) registry.register(agent);
const organization = new OrganizationService(registry);
organization.createOrganization("org", "AGENTOS", boss.id, "now");
organization.addManager(managerA.id, "frontend");
organization.addManager(managerB.id, "backend");
organization.addWorker(worker.id, "frontend");
const messages = new AgentMessageService();
const conference = new ConferenceRoomService(registry, messages);
const meeting = conference.createMeeting({ id: "meeting", projectId: "project", calledBy: boss.id, participants: [managerA.id], agenda: "Allocate" });
conference.startMeeting(meeting.id);
const decision = conference.createDecision({ id: "decision", meetingId: meeting.id, decidedBy: boss.id, decisionType: "ASSIGN_MANAGER", summary: "Manager A owns the task", taskIds: ["task"], managerId: managerA.id });
conference.completeMeeting(meeting.id);
const dispatcher = new TaskDispatcher(registry);
const identity = new IdentityService();
for (const agent of [boss, managerA, managerB, worker]) identity.createIdentity({ agentId: agent.id, role: agent.role });
const wallet = new WalletService();
const security = new SecurityGateway(identity, new AccessControlService(identity), new RiskEngine(), new AnomalyDetectionService(), new KillSwitchService(identity, wallet));
const delegation = new DelegationService(registry, new DelegationFirewall(new PermissionEngine(), new PolicyEngine()), new ApprovalEngine(), dispatcher, security);
const dependencies = new DependencyManager();
const runtime = new AgentRuntime(registry, dispatcher, dependencies, delegation, new Scheduler(registry, dependencies, delegation), messages);
const execution = new ManagerAllocationService(registry, organization, conference, runtime, messages);
const tasks = new Map([["task", dispatcher.createTask("task", "Build frontend", "Build the frontend", boss.id, "high", 0)]]);
const audit = new AuditLedger();
const executionBus = new EventBus<ExecutionEvents>();
new AuditEventBridge(audit, executionBus, undefined, undefined, undefined, undefined, undefined, undefined, undefined, execution.events);
const created = execution.createAllocation({ id: "allocation", organizationId: "org", meetingId: meeting.id, decisionId: decision.id, projectId: "project", managerId: managerA.id, taskIds: ["task"], assignedBy: boss.id }, tasks);
if (created.decision !== "CREATED") throw new Error("Allocation creation failed");
if (tasks.get("task")?.assignedTo !== null) throw new Error("Allocation directly assigned a worker");
if (execution.approveAllocation("allocation", boss.id).decision !== "APPROVED") throw new Error("Allocation approval failed");
const active = execution.activateAllocation("allocation", tasks);
if (active.decision !== "ACTIVATED" || active.scheduledTasks[0]?.assignedTo !== worker.id) throw new Error("Governed allocation activation failed");
if (tasks.get("task")?.assignedTo !== worker.id) throw new Error("Worker did not receive the allocated task");
if (messages.getByAgent(managerA.id).length < 2) throw new Error("Manager notifications missing");
if (audit.getByType("MANAGER_ALLOCATION_CREATED").length !== 1) throw new Error("Allocation creation was not audited");
if (audit.getByType("MANAGER_ALLOCATION_APPROVED").length !== 1) throw new Error("Allocation approval was not audited");
if (audit.getByType("MANAGER_ALLOCATION_ACTIVATED").length !== 1) throw new Error("Allocation activation was not audited");
if (!audit.verifyIntegrity()) throw new Error("Allocation audit integrity failed");
console.log("Manager allocation integration passed.");
